/*
 * Copyright Kroxylicious Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package io.kroxylicious.krpccodegen.main;

import java.nio.ByteBuffer;

import org.apache.kafka.common.protocol.ByteBufferAccessor;
import org.apache.kafka.common.protocol.Message;
import org.apache.kafka.common.protocol.MessageSizeAccumulator;
import org.apache.kafka.common.protocol.ObjectSerializationCache;

/**
 * Utility for serializing and deserializing Kafka {@link Message} objects to/from
 * raw bytes using the standard two-pass serialization protocol.
 * <p>
 * Works with both the real Kafka codec classes from {@code kafka-clients} and with
 * dynamically-compiled codec classes generated by the kroxylicious-krpc-plugin,
 * since both implement the same {@link Message} interface.
 */
class MessageSerdes {

    private MessageSerdes() {
    }

    /**
     * Serializes a {@link Message} to bytes at the given version.
     */
    static byte[] write(Message message, short version) {
        ObjectSerializationCache cache = new ObjectSerializationCache();
        MessageSizeAccumulator sizeAccumulator = new MessageSizeAccumulator();
        message.addSize(sizeAccumulator, cache, version);
        ByteBuffer buffer = ByteBuffer.allocate(sizeAccumulator.totalSize());
        message.write(new ByteBufferAccessor(buffer), cache, version);
        buffer.flip();
        byte[] bytes = new byte[buffer.remaining()];
        buffer.get(bytes);
        return bytes;
    }

    /**
     * Deserializes bytes into the given {@link Message} instance at the given version.
     *
     * @return the populated {@code message} instance (same object, for chaining)
     */
    static <T extends Message> T read(T message, byte[] bytes, short version) {
        message.read(new ByteBufferAccessor(ByteBuffer.wrap(bytes)), version);
        return message;
    }
}
